/**: # Global Params
  ros__parameters:
      traj_name: "buggycourse_pavedline.json"

NAND:
  bnyahaj:
    ros__parameters:
      teensy_name: "ttyUSB0"

  NAND_controller:
    ros__parameters:
      dist: 0.0
      stateTopic: "self/state"
      trajectoryTopic: "self/cur_traj"
      steeringTopic: "input/steering"
      useHeadingRate: true
      controllerName: "controller"
      # traj_name: "buggycourse_safe.json"
      controller: "stanley"
