/**: # Global Params
  ros__parameters:
      traj_name: "buggycourse_safe.json"

SC:
  bnyahaj:
    ros__parameters:
      teensy_name: "ttyUSB0"

  SC_controller:
    ros__parameters:
      dist: 0.0
      # traj_name: "buggycourse_safe.json"
      controller: "stanley"

  SC_path_planner:
    ros__parameters:
      # traj_name: "buggycourse_safe.json"
      curb_name: "buggycourse_curb.json"